services:
  mongo:
    image: mongo:7-jammy
    container_name: voizeforms-mongo
    environment:
      - MONGO_INITDB_DATABASE=voizeforms
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:-mongodb://mongo:27017/voizeforms}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voizeforms
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-dev-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-dev-client-secret}
      - ALLOWED_EMAILS=${ALLOWED_EMAILS:-dev@example.com}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
