ktor:
  application:
    modules: [ com.voizeforms.ApplicationKt.module ]
  deployment:
    port: 8080
    host: 0.0.0.0

mongodb:
  connectionString: ${MONGODB_CONNECTION_STRING:"mongodb://mongo:27017/voizeforms"}
  database: voizeforms
