name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:  # Allow manual triggers

env:
  PROJECT_ID: voizeforms
  SERVICE_NAME: voizeforms
  REGION: europe-west1
  REPOSITORY: europe-west1-docker.pkg.dev/voizeforms/voizeforms
  IMAGE_NAME: voizeforms

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          # Also tag as latest
          docker tag ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Download and Push Container
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Tag and Push Container
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          docker tag voizeforms:${{ github.sha }} ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag voizeforms:${{ github.sha }} ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated'  # Remove this if you want to restrict access
          env_vars: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            ALLOWED_EMAILS=${{ secrets.ALLOWED_EMAILS }}
            BASE_URL=https://voize.lucaskummer.com

      - name: Show Output
        run: |
          echo "Deployed to ${{ steps.deploy.outputs.url }}" 